### ISSUE TITLE
error with clean emails

### ISSUE THREAD

**Issue by dinomonkey2** [m0nkeyplay/hibp_quickCheck#1]
when the email does not have a breach i get this error
<img width="787" alt="test" src="https://user-images.githubusercontent.com/58213806/69625246-1a17b700-103e-11ea-97a9-a4ac0ecf74af.PNG">

**Comment by m0nkeyplay** [comment]
Sorry it took so long to get back. I just saw this. 

The issue is fixed. When an email isn’t found it gave a different result.  That has been tested and fixed searching for the correct error code.
